### ISSUE TITLE
Package Control Warning

### ISSUE THREAD

**Issue by justnealpatel** [SublimeText/ExtractSublimePackage#3]
It gives you a warning that when extracting a package for you to delete the Package Control folder from /Packages/ but when you initiate Extract Package Control it creates a Package Control folder on its own so the warning will always pop up. This is small, but it keeps asking to restart Sublime Text.

Sublime Text Build 3126
macOS Sierra 10.12

**Comment by Kristinita** [comment]
+1.

### 1. Request

It would be nice, if Package Control will ignore, when user extracts all packages.

### 2. Justification

<kbd>Ctrl+Shift+P</kbd> → `Extract Sublime Package: Extract All Packages` → I get popup:

![Package Control](http://i.imgur.com/GcsnRWO.png)

Sublime Text console output:

```
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
error: Package Control

It appears you have Package Control installed as both a .sublime-package file and a directory inside of the Packages folder.

To fix this issue, please:

1. Open the "Preferences" menu
2. Select "Browse Packages…"
3. Delete the folder "Package Control"
4. Restart Sublime Text
```

I need to make these actions to continue working in Sublime Text.

### 3. Desirable behavior

Package Control package don't extract if user select `Extract Sublime Package: Extract All Packages`.

### 4. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Sublime Text:**
Build 3126


Thanks.

**Comment by FichteFoll** [comment]
This is a safety/counter measure from Package Control and not an issue with this package.

You should manually intervene if extracting "all packages" is not what you want.

PS: I find the purpose of command questionable anyway because it is much more likely to cause issues than solve any.

**Comment by Kristinita** [comment]
@FichteFoll , yes, but the problem don't solved. It would be nice, if ExtractSublimePackage will not extract Package Control to new folder.

Thanks.

**Comment by FichteFoll** [comment]
This is a "wontfix" as in "not this package's fault". I don't know who maintains this package (probably nobody), but I personally would *not* make a special case for Package Control for this.

I would either: 

1. remove the command completely because it's error-prone (as indicated by this issue) and bad practice in general for several reasons (actually, the entire package is bad), or
2. tell the users to manually remove either the original `.sublime-package` or the resulting extracted package (whichever they prefer), since this could happen to *any package* and not just PC.

I chose 2 because it was easier for me.

**Comment by Kristinita** [comment]
@FichteFoll , I don't think, that close unfixed issue — is the best idea.

This is open source: maybe some developer see open issue and fix it.

Thanks.

**Comment by FichteFoll** [comment]
Okay, I can do that. Just don't get your hopes up. I'd rather remove this command than fix it, tbh.

**Comment by santwijaya** [comment]
I found the same popup, to remove this popup, follow this steps (tested in windows)
1. Open path ~\AppData\Roaming\Sublime Text 3\Installed Packages from C:/ directtory
2. Delete Folder 'Package Control'
3. Just restart sublime. 

cheers

**Comment by 0x87654321** [comment]
I met the same problem, it's just because the software recorded the packages I installed.
You can solve it by remove the corresponding file under file path : ...\Sublime Text 3\Installed Packages.

**Comment by FichteFoll** [comment]
Since nobody maintains this package, I took it upon myself to decide (as before) that this will not be fixed. This package's functionality is very barebones and that's a good thing because it is predictable, but also allows users to shoot themselves in the foot. I don't know why anyone who doesn't understand what Package Control *is* or what it does would want to extract it into their Packages folder, but if they wish to do so then they will be my guests.

Regardless, I have removed the "Extract All Packages" command because it doesn't do anything good (but be my guest to convince me otherwise) and strongly suggest to use https://odatnurd.net/overrideaudit/ instead of this package, because it properly protects you from shooting yourself in the foot. Or at least to a reasonable amount.
